# Generated by Django 5.2.17 on 2026-09-16 12:29

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0008_session_pending_revoke"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.itemgroup",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_normalized", models.CharField(db_index=True, max_length=200)),
                ("barcode", models.CharField(blank=True, default="", max_length=64)),
                ("sale_price_minor", models.BigIntegerField(default=0)),
                ("price_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unit",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="catalog.itemgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("factor_milli", models.BigIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="catalog.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("alias", models.CharField(max_length=120)),
                ("alias_normalized", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="catalog_alias_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "alias_normalized"),
                        name="catalog_alias_unique_per_tenant",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="itemgroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="catalog_group_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemgroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="catalog_group_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="catalog_item_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("tenant", "barcode"),
                name="catalog_item_barcode_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="catalog_itemunit_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.UniqueConstraint(
                fields=("item", "unit"), name="catalog_itemunit_item_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.CheckConstraint(
                condition=models.Q(("factor_milli__gt", 0)), name="catalog_itemunit_factor_pos"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("catalog_itemgroup"), rls.disable_sql("catalog_itemgroup")
        ),
        migrations.RunSQL(rls.enable_sql("catalog_item"), rls.disable_sql("catalog_item")),
        migrations.RunSQL(rls.enable_sql("catalog_itemunit"), rls.disable_sql("catalog_itemunit")),
        migrations.RunSQL(
            rls.enable_sql("catalog_itemalias"), rls.disable_sql("catalog_itemalias")
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_item",
                "catalog_item_group_same_tenant",
                "tenant_id, group_id",
                "catalog_itemgroup",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_item", "catalog_item_group_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_item",
                "catalog_item_unit_same_tenant",
                "tenant_id, base_unit_id",
                "core_unit",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_item", "catalog_item_unit_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_itemunit",
                "catalog_itemunit_item_same_tenant",
                "tenant_id, item_id",
                "catalog_item",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_itemunit", "catalog_itemunit_item_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_itemunit",
                "catalog_itemunit_unit_same_tenant",
                "tenant_id, unit_id",
                "core_unit",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_itemunit", "catalog_itemunit_unit_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_itemalias",
                "catalog_itemalias_item_same_tenant",
                "tenant_id, item_id",
                "catalog_item",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_itemalias", "catalog_itemalias_item_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_itemgroup",
                "catalog_itemgroup_parent_same_tenant",
                "tenant_id, parent_id",
                "catalog_itemgroup",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_itemgroup", "catalog_itemgroup_parent_same_tenant"),
        ),
    ]
