# Generated by Django 5.2.17 on 2026-09-16 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_catalog"),
        ("core", "0009_unit_decimal_places"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemUnitFactorChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("old_factor_milli", models.BigIntegerField()),
                ("new_factor_milli", models.BigIntegerField()),
                ("prior_lines", models.PositiveIntegerField(default=0)),
                ("changed_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="image_data_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="item",
            name="image_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemunit",
            name="barcode",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="itemunit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("tenant", "barcode"),
                name="catalog_itemunit_barcode_per_tenant",
            ),
        ),
        migrations.AddField(
            model_name="itemunitfactorchange",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemunitfactorchange",
            name="item_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="catalog.itemunit",
            ),
        ),
        migrations.AddField(
            model_name="itemunitfactorchange",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunitfactorchange",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="catalog_itemunitfactorchange_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("catalog_itemunitfactorchange"),
            rls.disable_sql("catalog_itemunitfactorchange"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_itemunitfactorchange",
                "catalog_itemunitfactorchange_unit_same_tenant",
                "tenant_id, item_unit_id",
                "catalog_itemunit",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql(
                "catalog_itemunitfactorchange", "catalog_itemunitfactorchange_unit_same_tenant"
            ),
        ),
    ]
