# Generated by Django 5.2.17 on 2026-09-16 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.ids
from core.db import rls


def seed_first_prices(apps, schema_editor):
    """كل صنف قائم يحصل على سطر سعر أول من سعره الحالي ووقته (السعر سلسلة تواريخ لا قيمة واحدة)."""
    Item = apps.get_model("catalog", "Item")
    ItemPrice = apps.get_model("catalog", "ItemPrice")
    for item in Item.objects.all():
        ItemPrice.objects.create(
            tenant_id=item.tenant_id,
            item_id=item.id,
            price_minor=item.sale_price_minor,
            effective_from=item.price_updated_at or item.created_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_cat02_cat03"),
        ("core", "0009_unit_decimal_places"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("file_sha256", models.CharField(max_length=64)),
                ("rows", models.JSONField(default=list)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="previewed", max_length=16)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("price_minor", models.BigIntegerField()),
                ("effective_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("changed_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=120)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalog.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="catalog.priceimportbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("proposed_price_minor", models.BigIntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("requested_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=16)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_requests",
                        to="catalog.item",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="catalog_pricechangerequest_tenant_id"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="priceimportbatch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="catalog_priceimportbatch_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="priceimportbatch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "file_sha256"), name="catalog_priceimportbatch_file_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemprice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="catalog_itemprice_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_minor__gte", 0)), name="catalog_itemprice_nonneg"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("catalog_itemprice"), rls.disable_sql("catalog_itemprice")
        ),
        migrations.RunSQL(
            rls.enable_sql("catalog_pricechangerequest"),
            rls.disable_sql("catalog_pricechangerequest"),
        ),
        migrations.RunSQL(
            rls.enable_sql("catalog_priceimportbatch"), rls.disable_sql("catalog_priceimportbatch")
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_itemprice",
                "catalog_itemprice_item_same_tenant",
                "tenant_id, item_id",
                "catalog_item",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_itemprice", "catalog_itemprice_item_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_itemprice",
                "catalog_itemprice_batch_same_tenant",
                "tenant_id, batch_id",
                "catalog_priceimportbatch",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("catalog_itemprice", "catalog_itemprice_batch_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "catalog_pricechangerequest",
                "catalog_pricechangerequest_item_same_tenant",
                "tenant_id, item_id",
                "catalog_item",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql(
                "catalog_pricechangerequest", "catalog_pricechangerequest_item_same_tenant"
            ),
        ),
        migrations.RunPython(seed_first_prices, migrations.RunPython.noop),
    ]
