# Generated by Django 5.2.17 on 2026-09-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_prices_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="alert_threshold_milli",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
