# Generated by Django 5.2.17 on 2026-09-18 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_item_alert_threshold"),
        ("core", "0010_device_freeze_wipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=12)),
                ("file_name", models.CharField(max_length=200)),
                ("file_sha256", models.CharField(max_length=64)),
                ("mapping", models.JSONField(default=dict)),
                ("rows", models.JSONField(default=list)),
                ("create_count", models.PositiveIntegerField(default=0)),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("decision_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="previewed", max_length=16)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="catalog_dataimportbatch_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "file_sha256"),
                        name="catalog_dataimportbatch_file_per_tenant",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("catalog_dataimportbatch"), rls.disable_sql("catalog_dataimportbatch")
        ),
    ]
