# Generated by Django 5.2.17 on 2026-09-20 00:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("stingops", "0001_operator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("maintenance", "صيانة مجدولة"), ("notice", "إعلان")],
                        default="maintenance",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(max_length=600)),
                (
                    "audience",
                    models.CharField(
                        choices=[("all", "كل المتاجر"), ("market", "متاجر ذات مزامنة سوق فعّالة")],
                        default="market",
                        max_length=10,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("scheduled", "مجدول"),
                            ("cancelled", "أُلغي"),
                            ("done", "انتهى"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("audience_count", models.PositiveIntegerField(default=0)),
                ("created_by_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_by_name", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ProofClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("proof_id", models.UUIDField()),
                ("claimed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handover_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
    ]
