# Generated by Django 5.2.17 on 2026-09-20 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0002_proofs_announcements"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("sms_primary", "الرسائل النصية — المزوّد الأساسي"),
                            ("sms_fallback", "الرسائل النصية — الاحتياطي"),
                            ("push", "إشعارات التطبيق"),
                            ("email", "البريد التشغيلي"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("up", "يعمل"), ("down", "متعذّر")], default="up", max_length=6
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("changed_by_name", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
    ]
