# Generated by Django 5.2.17 on 2026-09-20 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0003_channel_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerBackup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("nightly", "ليلية"), ("weekly", "أسبوعية")],
                        default="nightly",
                        max_length=8,
                    ),
                ),
                ("taken_at", models.DateTimeField()),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "صالحة"), ("failed", "فشلت"), ("incomplete", "لم تكتمل")],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("table_counts", models.JSONField(blank=True, default=dict)),
                ("location_ref", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RestoreDrill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("isolated", "بيئة معزولة"), ("live", "بيانات حيّة")],
                        default="isolated",
                        max_length=8,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("ok", "ناجحة"), ("failed", "فشلت"), ("blocked", "مُنعت")],
                        default="ok",
                        max_length=8,
                    ),
                ),
                ("rpo_minutes", models.PositiveIntegerField(default=0)),
                ("rto_minutes", models.PositiveIntegerField(default=0)),
                ("integrity_pct", models.PositiveSmallIntegerField(default=0)),
                ("detail", models.CharField(blank=True, default="", max_length=400)),
                ("by_name", models.CharField(max_length=200)),
                ("second_approver_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "environment_confirmation",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "backup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drills",
                        to="stingops.serverbackup",
                    ),
                ),
            ],
        ),
    ]
