# Generated by Django 5.2.17 on 2026-09-20 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0004_server_backups"),
    ]

    operations = [
        migrations.CreateModel(
            name="M0Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("month", models.CharField(max_length=7, unique=True)),
                ("computed_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("computed_by_name", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="DailyCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("key", models.CharField(max_length=40)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "key"), name="stingops_dailycounter_day_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OpsFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                (
                    "scope_kind",
                    models.CharField(choices=[("plan", "باقة"), ("env", "بيئة")], max_length=4),
                ),
                ("scope", models.CharField(max_length=40)),
                ("enabled", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("changed_by_name", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "scope_kind", "scope"), name="stingops_opsflag_key_scope"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("plan_code", models.CharField(max_length=20)),
                ("feature", models.CharField(max_length=40)),
                ("enabled", models.BooleanField(default=True)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("changed_by_name", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan_code", "feature"),
                        name="stingops_planentitlement_plan_feature",
                    )
                ],
            },
        ),
    ]
