# Generated by Django 5.2.17 on 2026-09-21 08:15

import django.utils.timezone
from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0005_m0_entitlements"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("whatsapp", models.CharField(max_length=40)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "channel",
                    models.CharField(
                        choices=[("whatsapp", "واتساب"), ("call", "مكالمة"), ("email", "بريد")],
                        max_length=8,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("source_path", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("handled_by_name", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "indexes": [models.Index(fields=["created_at"], name="stingops_demoreq_created")],
            },
        ),
    ]
