# Generated by Django 5.2.17 on 2026-09-21 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_subscription_ops"),
        ("stingops", "0006_demo_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("extend", "تمديد"),
                            ("plan_change", "تغيير الباقة"),
                            ("suspend", "إيقاف"),
                            ("resume", "استئناف"),
                            ("note", "ملاحظة"),
                            ("proof_approved", "اعتماد إثبات"),
                            ("proof_rejected", "رفض إثبات"),
                        ],
                        max_length=16,
                    ),
                ),
                ("days", models.IntegerField(default=0)),
                ("from_plan", models.CharField(blank=True, default="", max_length=20)),
                ("to_plan", models.CharField(blank=True, default="", max_length=20)),
                ("expires_before", models.DateTimeField(blank=True, null=True)),
                ("expires_after", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("by_name", models.CharField(max_length=200)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "at"], name="stingops_subevent_tenant_at")
                ],
            },
        ),
    ]
