# Generated by Django 5.2.17 on 2026-09-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0007_subscription_ops"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequest",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "جديد"),
                    ("contacted", "تواصلنا"),
                    ("converted", "تحوّل"),
                    ("closed", "أُغلق"),
                ],
                default="new",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="demorequest",
            index=models.Index(fields=["status", "created_at"], name="stingops_demoreq_status"),
        ),
    ]
