# Generated by Django 5.2.17 on 2026-09-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0008_demo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("extend", "تمديد"),
                    ("plan_change", "تغيير الباقة"),
                    ("suspend", "إيقاف"),
                    ("resume", "استئناف"),
                    ("note", "ملاحظة"),
                    ("limits", "زيادة حدود"),
                    ("proof_approved", "اعتماد إثبات"),
                    ("proof_rejected", "رفض إثبات"),
                ],
                max_length=16,
            ),
        ),
    ]
