# Generated by Django 5.2.17 on 2026-09-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0009_subevent_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorprofile",
            name="role",
            field=models.CharField(
                choices=[("admin", "مدير المنصة"), ("support", "الدعم")],
                default="admin",
                max_length=10,
            ),
        ),
    ]
