# Generated by Django 5.2.17 on 2026-09-29 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_pricing_decisions"),
        ("stingops", "0010_operator_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="operatorprofile",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
