# Generated by Django 5.2.17 on 2026-10-02 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids


def backfill_keys(apps, schema_editor):
    """مفاتيح التكرار للطلبات القائمة (0005 §١٤٧) — بالتطبيع نفسه في `stingops.demo_public`."""
    from stingops.demo_public import name_key, phone_key

    DemoRequest = apps.get_model("stingops", "DemoRequest")
    for r in DemoRequest.objects.all().only("id", "name", "whatsapp", "email"):
        DemoRequest.objects.filter(id=r.id).update(
            phone_key=phone_key(r.whatsapp),
            name_key=name_key(r.name),
            email=r.email.strip().lower(),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0011_owner_decisions_138"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequest",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="name_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="phone_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=16),
        ),
        migrations.CreateModel(
            name="DemoRequestComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField()),
                ("author_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="stingops.demorequest",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["request", "created_at"], name="stingops_democomment_req")
                ],
            },
        ),
        migrations.RunPython(backfill_keys, migrations.RunPython.noop),
    ]
