# Generated by Django 5.2.17 on 2026-10-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stingops", "0012_demo_request_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverbackup",
            name="offsite_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serverbackup",
            name="offsite_key",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="serverbackup",
            name="offsite_note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="serverbackup",
            name="offsite_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="serverbackup",
            name="offsite_status",
            field=models.CharField(
                choices=[
                    ("none", "على الخادم وحده"),
                    ("ok", "خارج الخادم"),
                    ("failed", "فشل الرفع"),
                ],
                default="none",
                max_length=8,
            ),
        ),
    ]
