# Generated by Django 5.2.17 on 2026-09-19 17:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0023_portal_channels"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("buyer", "شراء"), ("seller", "بيع"), ("both", "شراء وبيع")],
                        default="buyer",
                        max_length=8,
                    ),
                ),
                (
                    "verification",
                    models.CharField(
                        choices=[
                            ("none", "لم يُطلب"),
                            ("draft", "مسوّدة الطلب"),
                            ("pending", "بانتظار المراجعة"),
                            ("needs_more", "أدلة ناقصة"),
                            ("verified", "منشأة موثَّقة المستندات"),
                            ("rejected", "مرفوض"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("business_address", models.CharField(blank=True, default="", max_length=300)),
                ("service_area_note", models.CharField(blank=True, default="", max_length=300)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("registry_doc_data_url", models.TextField(blank=True, default="")),
                ("registry_doc_name", models.CharField(blank=True, default="", max_length=200)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_name", models.CharField(blank=True, default="", max_length=200)),
                ("review_reasons", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_account_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant",), name="market_account_once_per_tenant"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("public_name", models.CharField(blank=True, default="", max_length=200)),
                ("category_line", models.CharField(blank=True, default="", max_length=120)),
                ("categories", models.JSONField(blank=True, default=list)),
                ("service_areas", models.JSONField(blank=True, default=list)),
                ("fulfilment", models.JSONField(blank=True, default=list)),
                ("published", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_profile_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant",), name="market_profile_once_per_tenant"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketaccount"), rls.disable_sql("market_marketaccount")
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketprofile"), rls.disable_sql("market_marketprofile")
        ),
    ]
