# Generated by Django 5.2.17 on 2026-09-19 17:21

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0001_market_account_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField(blank=True, null=True)),
                ("public_name", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.CharField(blank=True, default="", max_length=600)),
                ("unit_code", models.CharField(blank=True, default="", max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("pack_label", models.CharField(blank=True, default="", max_length=80)),
                ("price_minor", models.BigIntegerField(blank=True, null=True)),
                ("min_order_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("max_order_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("availability", models.CharField(default="available", max_length=12)),
                ("fulfilment_note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("public", "كل المشترين"),
                            ("private", "قائمة خاصة"),
                            ("followers", "متابعو منشأتك"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("private_party_ids", models.JSONField(blank=True, default=list)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("published", "منشور"),
                            ("expired", "منتهٍ"),
                            ("hidden", "مخفي"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("published_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "id"), name="market_offer_tenant_id")
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketoffer"), rls.disable_sql("market_marketoffer")
        ),
    ]
