# Generated by Django 5.2.17 on 2026-09-19 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0002_market_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketoffer",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MarketPriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("tiers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="market.marketoffer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketPriceListMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("buyer_tenant_id", models.UUIDField()),
                ("buyer_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "دعوة معلّقة"),
                            ("active", "نشطة"),
                            ("suspended", "موقوف"),
                        ],
                        default="invited",
                        max_length=10,
                    ),
                ),
                ("invited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("invite_expires_at", models.DateTimeField(blank=True, null=True)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="market.marketpricelist",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="marketpricelist",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="market_pricelist_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketpricelistmember",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="market_pricelistmember_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketpricelistmember",
            constraint=models.UniqueConstraint(
                fields=("tenant", "price_list", "buyer_tenant_id"),
                name="market_pricelistmember_once",
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketpricelist"), rls.disable_sql("market_marketpricelist")
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketpricelistmember"),
            rls.disable_sql("market_marketpricelistmember"),
        ),
    ]
