# Generated by Django 5.2.17 on 2026-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_price_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketaccount",
            name="publish_suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketaccount",
            name="publish_suspended_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="marketaccount",
            name="verified_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="delivery_fee_minor",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="delivery_free_over_minor",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="pickup_only",
            field=models.BooleanField(default=False),
        ),
    ]
