# Generated by Django 5.2.17 on 2026-09-19 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0004_badge_fees"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketFollow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("supplier_tenant_id", models.UUIDField()),
                ("supplier_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "متابَع"), ("cancelled", "أُلغيت")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("followed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_follow_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "supplier_tenant_id"), name="market_follow_once"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketfollow"), rls.disable_sql("market_marketfollow")
        ),
    ]
