# Generated by Django 5.2.17 on 2026-09-19 20:50

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0005_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("share", "مشاركة رابط"),
                            ("invite", "دعوة منشأة"),
                            ("authorization", "طلب تخويل"),
                        ],
                        default="share",
                        max_length=14,
                    ),
                ),
                ("target_offer_id", models.UUIDField(blank=True, null=True)),
                ("target_tenant_id", models.UUIDField(blank=True, null=True)),
                ("target_name", models.CharField(blank=True, default="", max_length=200)),
                ("message", models.CharField(blank=True, default="", max_length=300)),
                ("token_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "مرسَل"),
                            ("accepted", "قُبل"),
                            ("declined", "رُفض"),
                            ("revoked", "أُلغي"),
                            ("expired", "منتهٍ"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_tenant_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("signups", models.PositiveIntegerField(default=0)),
                ("publishes", models.PositiveIntegerField(default=0)),
                ("first_orders", models.PositiveIntegerField(default=0)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "id"), name="market_invite_tenant_id")
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("target_offer_id", models.UUIDField(blank=True, null=True)),
                ("target_tenant_id", models.UUIDField(blank=True, null=True)),
                ("target_label", models.CharField(blank=True, default="", max_length=300)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("impersonation", "انتحال اسم منشأة أو شارتها"),
                            ("misleading", "وصف مضلّل للمنتج أو وحدته"),
                            ("harmful", "محتوى غير لائق أو ضارّ"),
                            ("prohibited", "عرض لسلعة ممنوعة"),
                        ],
                        max_length=14,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=600)),
                ("evidence_data_url", models.TextField(blank=True, default="")),
                ("evidence_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("under_review", "قيد المراجعة"),
                            ("actioned", "أُجري إجراء"),
                            ("closed", "أُغلق بلا إجراء"),
                        ],
                        default="under_review",
                        max_length=14,
                    ),
                ),
                ("outcome", models.CharField(blank=True, default="", max_length=300)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "id"), name="market_report_tenant_id")
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketinvite"), rls.disable_sql("market_marketinvite")
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketreport"), rls.disable_sql("market_marketreport")
        ),
    ]
