# Generated by Django 5.2.17 on 2026-09-19 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0006_invites_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("op_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("order", "طلب"), ("quote", "طلب سعر")],
                        default="order",
                        max_length=6,
                    ),
                ),
                ("supplier_tenant_id", models.UUIDField()),
                ("supplier_name", models.CharField(max_length=200)),
                ("buyer_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "بانتظار رد المورد"),
                            ("quoted", "عرض سعر من المورد"),
                            ("accepted", "مقبول"),
                            ("rejected", "مرفوض"),
                            ("preparing", "قيد التجهيز"),
                            ("delivered", "سُلِّم"),
                            ("received", "استُلم"),
                            ("cancelled", "أُلغي"),
                            ("disputed", "خلاف مفتوح"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("currency", models.CharField(default="SDG", max_length=3)),
                ("lines", models.JSONField(blank=True, default=list)),
                ("delivery_to", models.CharField(blank=True, default="", max_length=200)),
                ("fees_label", models.CharField(blank=True, default="", max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=600)),
                ("response_hours", models.PositiveIntegerField(default=72)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "id"), name="market_order_tenant_id"),
                    models.UniqueConstraint(
                        fields=("tenant", "op_id"), name="market_order_op_once"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketorder"), rls.disable_sql("market_marketorder")
        ),
    ]
