# Generated by Django 5.2.17 on 2026-09-19 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0007_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketorder",
            name="agreed_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MarketOrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("side", models.CharField(default="buyer", max_length=8)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.CharField(blank=True, default="", max_length=400)),
                ("ref_label", models.CharField(blank=True, default="", max_length=80)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="market.marketorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_orderevent_tenant_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketOrderVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("request", "طلب المشتري"),
                            ("quote", "عرض المورد"),
                            ("revision", "تعديل لاحق من المورد"),
                        ],
                        default="request",
                        max_length=10,
                    ),
                ),
                ("author_side", models.CharField(default="buyer", max_length=8)),
                ("lines", models.JSONField(blank=True, default=list)),
                ("delivery_fee_minor", models.BigIntegerField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=600)),
                ("summary", models.CharField(blank=True, default="", max_length=300)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="market.marketorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_orderversion_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("order", "number"), name="market_orderversion_number_once"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketorderversion"),
            rls.disable_sql("market_marketorderversion"),
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketorderevent"), rls.disable_sql("market_marketorderevent")
        ),
    ]
