# Generated by Django 5.2.17 on 2026-09-19 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0008_order_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketorderversion",
            name="delivery_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketorderversion",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MarketShipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                ("lines", models.JSONField(blank=True, default=list)),
                ("carrier_ref", models.CharField(blank=True, default="", max_length=120)),
                ("eta_note", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.CharField(blank=True, default="", max_length=400)),
                ("shipped_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="market.marketorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_shipment_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("order", "number"), name="market_shipment_number_once"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketshipment"), rls.disable_sql("market_marketshipment")
        ),
    ]
