# Generated by Django 5.2.17 on 2026-09-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0009_shipments"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketorder",
            name="cancel_reason",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="remaining_cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketshipment",
            name="dispute_opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketshipment",
            name="received_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="marketshipment",
            name="received_lines",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
