# Generated by Django 5.2.17 on 2026-09-19 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0010_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("lines", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "مفتوح"), ("closed", "مُغلق")],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("turn", models.CharField(default="supplier", max_length=8)),
                ("turn_deadline", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, default=list)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("return", "مرتجع"),
                            ("credit", "خصم/إشعار دائن"),
                            ("accept", "قبول بالحالة"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                ("outcome_ref", models.CharField(blank=True, default="", max_length=120)),
                ("mediator_requested_at", models.DateTimeField(blank=True, null=True)),
                ("opened_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="market.marketorder",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="market.marketshipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_dispute_tenant_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                ("lines", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "بانتظار موافقة"),
                            ("approved", "موافَق عليه"),
                            ("partial", "موافقة جزئية"),
                            ("rejected", "مرفوض"),
                            ("executed", "نُفِّذ"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("decision_note", models.CharField(blank=True, default="", max_length=400)),
                ("requested_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="market.marketorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_return_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("order", "number"), name="market_return_number_once"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketreturn"), rls.disable_sql("market_marketreturn")
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketdispute"), rls.disable_sql("market_marketdispute")
        ),
    ]
