# Generated by Django 5.2.17 on 2026-09-19 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0011_returns_disputes"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketorder",
            name="paid_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="reconciling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketorder",
            name="restore_point",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketorderevent",
            name="decision",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="marketorderevent",
            name="decision_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="marketorderevent",
            name="needs_decision",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MarketPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("supplier_tenant_id", models.UUIDField()),
                ("number", models.PositiveIntegerField(default=0)),
                ("amount_minor", models.BigIntegerField()),
                ("transfer_ref", models.CharField(max_length=120)),
                ("transferred_on", models.DateField()),
                ("allocations", models.JSONField(blank=True, default=list)),
                ("evidence_name", models.CharField(blank=True, default="", max_length=200)),
                ("evidence_data_url", models.TextField(blank=True, default="")),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "مسجَّل — غير مطابق"),
                            ("matched", "مطابَق"),
                            ("rejected", "مرفوض"),
                        ],
                        default="recorded",
                        max_length=10,
                    ),
                ),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("matched_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("decision_note", models.CharField(blank=True, default="", max_length=300)),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("uploaded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="market.marketorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_payment_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "supplier_tenant_id", "transfer_ref"),
                        name="market_payment_ref_once",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketpayment"), rls.disable_sql("market_marketpayment")
        ),
    ]
