# Generated by Django 5.2.17 on 2026-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0012_payments_restore"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketdispute",
            name="mediator_note",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AddField(
            model_name="marketdispute",
            name="referred_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="marketdispute",
            name="referred_external_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_decision_note",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_doc_data_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_doc_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_note",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_reviewer_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="appeal_status",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="suspended_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="suspended_reason",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AddField(
            model_name="marketoffer",
            name="suspended_reason_code",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
    ]
