# Generated by Django 5.2.17 on 2026-09-20 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0013_suspension_mediation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketItemMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("counterparty_tenant_id", models.UUIDField()),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(max_length=200)),
                ("unit_code", models.CharField(max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("offer_id", models.UUIDField()),
                ("offer_name", models.CharField(max_length=200)),
                ("offer_unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("offer_pack_label", models.CharField(blank=True, default="", max_length=120)),
                ("offer_version", models.PositiveIntegerField(default=1)),
                ("factor_milli", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "مطابَق"),
                            ("needs_definition", "ناقص تعريف"),
                            ("needs_review", "يحتاج مراجعة"),
                        ],
                        default="matched",
                        max_length=18,
                    ),
                ),
                ("confirmed_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_itemmapping_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "counterparty_tenant_id", "offer_id"),
                        name="market_itemmapping_offer_once",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketPartyLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("party_id", models.UUIDField()),
                ("party_name", models.CharField(max_length=200)),
                ("counterparty_tenant_id", models.UUIDField()),
                ("counterparty_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "بانتظار موافقة المنشأة"),
                            ("accepted", "مربوط"),
                            ("rejected", "رُفض"),
                            ("cancelled", "أُلغي"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("requested_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_partylink_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketpartylink"), rls.disable_sql("market_marketpartylink")
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketitemmapping"), rls.disable_sql("market_marketitemmapping")
        ),
    ]
