# Generated by Django 5.2.17 on 2026-09-20 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0014_link_parties_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketDocumentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "استلام مقابل شحنة"),
                            ("return", "مرتجع إلى مستند عكسي"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("created", "أُنشئ من الشحنة"),
                            ("attached", "رُبط بمستند يدوي قائم"),
                        ],
                        default="created",
                        max_length=8,
                    ),
                ),
                ("local_entity", models.CharField(max_length=40)),
                ("local_id", models.UUIDField()),
                ("local_number", models.CharField(blank=True, default="", max_length=40)),
                ("my_value_minor", models.BigIntegerField(default=0)),
                ("their_value_minor", models.BigIntegerField(default=0)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("settled_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("settlement_path", models.CharField(blank=True, default="", max_length=20)),
                ("settlement_note", models.CharField(blank=True, default="", max_length=400)),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doc_links",
                        to="market.marketreturn",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doc_links",
                        to="market.marketorder",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doc_links",
                        to="market.marketshipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_doclink_tenant_id"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("shipment__isnull", False)),
                        fields=("tenant", "shipment"),
                        name="market_doclink_shipment_once",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("market_return__isnull", False)),
                        fields=("tenant", "market_return"),
                        name="market_doclink_return_once",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketShipmentDistinct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("receipt_id", models.UUIDField()),
                ("confirmed_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("confirmed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distinct_confirmations",
                        to="market.marketshipment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_shipdistinct_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketdocumentlink"),
            rls.disable_sql("market_marketdocumentlink"),
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketshipmentdistinct"),
            rls.disable_sql("market_marketshipmentdistinct"),
        ),
    ]
