# Generated by Django 5.2.17 on 2026-09-20 13:02

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
        ("market", "0015_document_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPromotionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("offer_id", models.UUIDField()),
                ("offer_name", models.CharField(max_length=200)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("followers", "متابعو منشأتك"),
                            ("area", "منطقة خدمة"),
                            ("all", "كل المشترين"),
                        ],
                        max_length=10,
                    ),
                ),
                ("area", models.CharField(blank=True, default="", max_length=120)),
                ("duration_days", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة — بانتظار المالك"),
                            ("pricing_pending", "التسعير غير معتمد — يتواصل الفريق"),
                            ("cancelled", "أُلغي"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("prepared_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("requested_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="market_promotion_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("market_marketpromotionrequest"),
            rls.disable_sql("market_marketpromotionrequest"),
        ),
    ]
