# Generated by Django 5.2.17 on 2026-09-17 00:12

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0009_unit_decimal_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_normalized", models.CharField(db_index=True, max_length=200)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "phone_normalized",
                    models.CharField(blank=True, db_index=True, default="", max_length=32),
                ),
                ("credit_limit_minor", models.BigIntegerField(default=0)),
                ("is_customer", models.BooleanField(default=True)),
                ("is_supplier", models.BooleanField(default=False)),
                ("created_by_user_id", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distinct_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "id"), name="parties_party_tenant_id")
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("parties_party"),
            rls.disable_sql("parties_party"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "parties_party",
                "parties_party_distinct_same_tenant",
                "tenant_id, distinct_from_id",
                "parties_party",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("parties_party", "parties_party_distinct_same_tenant"),
        ),
    ]
