# Generated by Django 5.2.17 on 2026-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="party",
            name="aliases_normalized",
            field=models.TextField(blank=True, default=""),
        ),
    ]
