# Generated by Django 5.2.17 on 2026-09-17 15:07

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("parties", "0002_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.CreateModel(
            name="OpeningBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("customer_due", "عليها لنا"), ("supplier_owed", "لها علينا")],
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("reason", models.CharField(max_length=300)),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("business_date", models.DateField(blank=True, null=True)),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opening_balances",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="parties_openingbalance_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "party", "side"),
                        name="parties_openingbalance_once_per_side",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("parties_openingbalance"),
            rls.disable_sql("parties_openingbalance"),
        ),
    ]
