# Generated by Django 5.2.17 on 2026-09-17 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("parties", "0003_opening_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("receipt_number", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[("receipt", "سداد"), ("refund", "ردّ مبلغ")],
                        default="receipt",
                        max_length=8,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "نقداً"), ("bank", "تحويل بنكي")], max_length=8
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("branch_id", models.UUIDField()),
                ("device_id", models.UUIDField()),
                ("shift_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("matched_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("business_date", models.DateField()),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="parties_paymentreceipt_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "receipt_number"), name="parties_paymentreceipt_number"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("method", "bank")),
                        fields=("tenant", "reference"),
                        name="parties_paymentreceipt_bank_reference_once",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("parties_paymentreceipt"),
            rls.disable_sql("parties_paymentreceipt"),
        ),
    ]
