# Generated by Django 5.2.17 on 2026-09-17 17:13

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("parties", "0004_payment_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_sources",
                to="parties.party",
            ),
        ),
        migrations.CreateModel(
            name="PartyMerge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("movements_at_merge", models.PositiveIntegerField(default=0)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("undone_by_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merges_as_source",
                        to="parties.party",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merges_as_target",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="parties_partymerge_tenant_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReceiptCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("method", "تصحيح وسيلة الدفع"),
                            ("reverse", "عكس الحركة بالكامل"),
                            ("amount", "تصحيح المبلغ"),
                            ("date", "تصحيح تاريخ الأعمال"),
                        ],
                        max_length=8,
                    ),
                ),
                ("new_method", models.CharField(blank=True, default="", max_length=8)),
                ("new_reference", models.CharField(blank=True, default="", max_length=120)),
                ("new_amount_minor", models.BigIntegerField(blank=True, null=True)),
                ("new_business_date", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(max_length=300)),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="parties.paymentreceipt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="parties_receiptcorrection_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("parties_partymerge"),
            rls.disable_sql("parties_partymerge"),
        ),
        migrations.RunSQL(
            rls.enable_sql("parties_receiptcorrection"),
            rls.disable_sql("parties_receiptcorrection"),
        ),
    ]
