# Generated by Django 5.2.17 on 2026-09-17 19:16

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("parties", "0005_merge_correction"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("pdf", "تصدير PDF"), ("link", "مشاركة رابط")], max_length=8
                    ),
                ),
                ("range", models.CharField(default="30", max_length=8)),
                ("include_invoices", models.BooleanField(default=False)),
                ("include_branch", models.BooleanField(default=False)),
                ("file_name", models.CharField(max_length=240)),
                ("page_count", models.PositiveIntegerField(default=1)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("snapshot", models.JSONField(default=dict)),
                ("generated_by_user_id", models.UUIDField()),
                ("generated_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.PositiveIntegerField(default=0)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statement_exports",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="parties_statementexport_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("parties_statementexport"),
            rls.disable_sql("parties_statementexport"),
        ),
    ]
