# Generated by Django 5.2.17 on 2026-09-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0006_statement_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="marketing_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="party",
            name="marketing_opt_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
