# Generated by Django 5.2.17 on 2026-09-17 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("inventory", "0001_sale_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuarantineMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("base_qty_milli", models.BigIntegerField()),
                ("reason", models.CharField(max_length=24)),
                ("source_entity", models.CharField(blank=True, default="", max_length=64)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="inventory_quarantinemovement_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_quarantinemovement"),
            rls.disable_sql("inventory_quarantinemovement"),
        ),
    ]
