# Generated by Django 5.2.17 on 2026-09-17 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("inventory", "0002_sale_return"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("receipt_number", models.CharField(max_length=40)),
                ("party_id", models.UUIDField(blank=True, null=True)),
                ("supplier_name", models.CharField(max_length=200)),
                ("reference", models.CharField(max_length=120)),
                ("device_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("business_date", models.DateField()),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                ("unit_code", models.CharField(blank=True, default="", max_length=20)),
                ("factor_milli", models.BigIntegerField(default=1000)),
                ("qty_milli", models.BigIntegerField()),
                ("base_qty_milli", models.BigIntegerField()),
                ("unit_cost_minor", models.BigIntegerField(blank=True, null=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockOpening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("submitted", "أُرسلت للاعتماد"), ("approved", "معتمدة")],
                        default="submitted",
                        max_length=12,
                    ),
                ),
                ("created_by_user_id", models.UUIDField()),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("approved_by_user_id", models.UUIDField(blank=True, null=True)),
                ("approved_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockOpeningLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                ("unit_code", models.CharField(blank=True, default="", max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("factor_milli", models.BigIntegerField(default=1000)),
                ("qty_milli", models.BigIntegerField()),
                ("base_qty_milli", models.BigIntegerField()),
                ("unit_cost_minor", models.BigIntegerField(blank=True, null=True)),
                (
                    "opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockopening",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_goodsreceipt_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceiptline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_goodsreceiptline_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockopening",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_stockopening_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockopeningline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_stockopeningline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_goodsreceipt"),
            rls.disable_sql("inventory_goodsreceipt"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_goodsreceiptline"),
            rls.disable_sql("inventory_goodsreceiptline"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_stockopening"),
            rls.disable_sql("inventory_stockopening"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_stockopeningline"),
            rls.disable_sql("inventory_stockopeningline"),
        ),
    ]
