# Generated by Django 5.2.17 on 2026-09-17 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("inventory", "0003_receipt_opening"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.CreateModel(
            name="CountSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_number", models.CharField(max_length=40)),
                ("device_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("closed", "أُغلقت"), ("adjusted", "سُوّيت")],
                        default="closed",
                        max_length=12,
                    ),
                ),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("counted_qty_milli", models.BigIntegerField()),
                ("system_qty_milli", models.BigIntegerField(blank=True, null=True)),
                ("counted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.countsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("adjustment_number", models.CharField(max_length=40)),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.countsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAdjustmentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                ("book_qty_milli", models.BigIntegerField()),
                ("counted_qty_milli", models.BigIntegerField()),
                ("delta_milli", models.BigIntegerField()),
                ("reason", models.CharField(max_length=300)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockadjustment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="countsession",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_countsession_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="countline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_countline_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_stockadjustment_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_stockadjustmentline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_countsession"),
            rls.disable_sql("inventory_countsession"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_countline"),
            rls.disable_sql("inventory_countline"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_stockadjustment"),
            rls.disable_sql("inventory_stockadjustment"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_stockadjustmentline"),
            rls.disable_sql("inventory_stockadjustmentline"),
        ),
    ]
