# Generated by Django 5.2.17 on 2026-09-17 23:36

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("inventory", "0004_count_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("damage_number", models.CharField(max_length=40)),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                ("unit_code", models.CharField(blank=True, default="", max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("factor_milli", models.BigIntegerField(default=1000)),
                ("qty_milli", models.BigIntegerField()),
                ("base_qty_milli", models.BigIntegerField()),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("quarantine", "حجر — قابل للمراجعة"),
                            ("write_off", "هالك — خروج نهائي"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                ("value_minor", models.BigIntegerField(default=0)),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="inventory_damagerecord_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_damagerecord"),
            rls.disable_sql("inventory_damagerecord"),
        ),
    ]
