# Generated by Django 5.2.17 on 2026-09-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_damage_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockopeningline",
            name="line_no",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
