# Generated by Django 5.2.17 on 2026-09-18 05:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("inventory", "0006_opening_line_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("transfer_number", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "أُرسل"),
                            ("partially_received", "استُلم جزئياً"),
                            ("received", "استُلم"),
                            ("cancelled", "أُلغي"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("device_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("received_at_server", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "branch_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "branch_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("line_no", models.PositiveIntegerField(default=0)),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                ("unit_code", models.CharField(blank=True, default="", max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("factor_milli", models.BigIntegerField(default=1000)),
                ("qty_milli", models.BigIntegerField()),
                ("base_qty_milli", models.BigIntegerField()),
                ("received_base_milli", models.BigIntegerField(default=0)),
                ("value_minor", models.BigIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stocktransfer",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_stocktransfer_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransferline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_stocktransferline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_stocktransfer"),
            rls.disable_sql("inventory_stocktransfer"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_stocktransferline"),
            rls.disable_sql("inventory_stocktransferline"),
        ),
    ]
