# Generated by Django 5.2.17 on 2026-09-18 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("inventory", "0007_stock_transfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("receipt_number", models.CharField(max_length=40)),
                ("device_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("duplicate", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at_server", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="inventory.stocktransfer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("sent_base_milli", models.BigIntegerField()),
                ("received_base_milli", models.BigIntegerField()),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.transferreceipt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "transfer_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="inventory.stocktransferline",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="transferreceipt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_transferreceipt_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="transferreceiptline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_transferreceiptline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_transferreceipt"),
            rls.disable_sql("inventory_transferreceipt"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_transferreceiptline"),
            rls.disable_sql("inventory_transferreceiptline"),
        ),
    ]
