# Generated by Django 5.2.17 on 2026-09-19 13:41

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_campaign_messages"),
        ("inventory", "0008_transfer_receipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("supplier_id", models.UUIDField()),
                ("supplier_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("open", "مفتوحة"),
                            ("sent", "مُرسل"),
                            ("unsent", "لم يُرسل"),
                            ("partial", "استُلم جزئياً"),
                            ("received", "مستلَم"),
                            ("cancelled", "ملغى"),
                            ("closed", "مغلق"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("estimated_total_minor", models.BigIntegerField(blank=True, null=True)),
                ("lines_count", models.PositiveIntegerField(default=0)),
                ("created_by_user_id", models.UUIDField()),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_error", models.CharField(blank=True, default="", max_length=120)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.CharField(blank=True, default="", max_length=300)),
                ("cancelled_by_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(max_length=200)),
                ("unit_code", models.CharField(max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("factor_milli", models.BigIntegerField(default=1000)),
                ("qty_milli", models.BigIntegerField()),
                ("base_qty_milli", models.BigIntegerField()),
                ("est_unit_price_minor", models.BigIntegerField(blank=True, null=True)),
                ("received_base_qty_milli", models.BigIntegerField(default=0)),
                ("line_no", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_po_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="inventory_po_number_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_poline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_purchaseorder"), rls.disable_sql("inventory_purchaseorder")
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_purchaseorderline"),
            rls.disable_sql("inventory_purchaseorderline"),
        ),
    ]
