# Generated by Django 5.2.17 on 2026-09-19 14:03

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_campaign_messages"),
        ("inventory", "0009_purchase_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("supplier_id", models.UUIDField()),
                ("supplier_name", models.CharField(max_length=200)),
                (
                    "supplier_invoice_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "مسوّدة"), ("referred", "مُحال"), ("approved", "معتمد")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("total_minor", models.BigIntegerField(default=0)),
                ("due_days", models.PositiveIntegerField(default=30)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("created_by_user_id", models.UUIDField()),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by_user_id", models.UUIDField(blank=True, null=True)),
                ("approved_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("referred_to_name", models.CharField(blank=True, default="", max_length=200)),
                ("referred_at", models.DateTimeField(blank=True, null=True)),
                ("effects", models.JSONField(blank=True, default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseDocumentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(max_length=200)),
                ("unit_code", models.CharField(max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("factor_milli", models.BigIntegerField(default=1000)),
                ("ordered_qty_milli", models.BigIntegerField(default=0)),
                ("received_qty_milli", models.BigIntegerField()),
                ("base_qty_milli", models.BigIntegerField()),
                ("unit_price_minor", models.BigIntegerField()),
                ("est_unit_price_minor", models.BigIntegerField(blank=True, null=True)),
                ("excess_reason", models.CharField(blank=True, default="", max_length=300)),
                ("line_no", models.PositiveIntegerField(default=1)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.purchasedocument",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.purchaseorderline",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("supplier_id", models.UUIDField()),
                ("supplier_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "مسجَّل"),
                            ("partial", "مقبول جزئياً"),
                            ("accepted", "مقبول"),
                            ("rejected", "مرفوض"),
                        ],
                        default="recorded",
                        max_length=10,
                    ),
                ),
                ("total_minor", models.BigIntegerField(default=0)),
                ("accepted_minor", models.BigIntegerField(default=0)),
                ("supplier_note", models.CharField(blank=True, default="", max_length=300)),
                ("created_by_user_id", models.UUIDField()),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="inventory.purchasedocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(max_length=200)),
                ("unit_code", models.CharField(max_length=20)),
                ("unit_name", models.CharField(blank=True, default="", max_length=60)),
                ("factor_milli", models.BigIntegerField(default=1000)),
                ("qty_milli", models.BigIntegerField()),
                ("base_qty_milli", models.BigIntegerField()),
                ("unit_price_minor", models.BigIntegerField()),
                ("reason", models.CharField(max_length=300)),
                ("accepted_qty_milli", models.BigIntegerField(blank=True, null=True)),
                ("supplier_note", models.CharField(blank=True, default="", max_length=300)),
                ("line_no", models.PositiveIntegerField(default=1)),
                (
                    "document_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="inventory.purchasedocumentline",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.purchasereturn",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_pdoc_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="inventory_pdoc_number_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocumentline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_pdocline_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_pret_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="inventory_pret_number_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturnline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="inventory_pretline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_purchasedocument"),
            rls.disable_sql("inventory_purchasedocument"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_purchasedocumentline"),
            rls.disable_sql("inventory_purchasedocumentline"),
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_purchasereturn"), rls.disable_sql("inventory_purchasereturn")
        ),
        migrations.RunSQL(
            rls.enable_sql("inventory_purchasereturnline"),
            rls.disable_sql("inventory_purchasereturnline"),
        ),
    ]
