# Generated by Django 5.2.17 on 2026-09-17 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0009_unit_decimal_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("branch_id", models.UUIDField()),
                ("device_id", models.UUIDField()),
                ("requested_by_user_id", models.UUIDField()),
                ("requested_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("mode", models.CharField(max_length=8)),
                ("value", models.CharField(max_length=32)),
                ("cap", models.CharField(max_length=32)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("cart_total_minor", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار الاعتماد"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_by_user_id", models.UUIDField(blank=True, null=True)),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="sales_discountoverride_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_discountoverride"),
            rls.disable_sql("sales_discountoverride"),
        ),
    ]
