# Generated by Django 5.2.17 on 2026-09-17 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("branch_id", models.UUIDField()),
                ("device_id", models.UUIDField()),
                ("shift_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("party_id", models.UUIDField(blank=True, null=True)),
                ("invoice_number", models.CharField(max_length=40)),
                ("subtotal_minor", models.BigIntegerField()),
                ("discount_mode", models.CharField(blank=True, default="", max_length=8)),
                ("discount_value", models.CharField(blank=True, default="", max_length=32)),
                ("discount_minor", models.BigIntegerField(default=0)),
                ("discount_reason", models.CharField(blank=True, default="", max_length=300)),
                ("total_minor", models.BigIntegerField()),
                ("cash_minor", models.BigIntegerField(default=0)),
                ("bank_minor", models.BigIntegerField(default=0)),
                ("credit_minor", models.BigIntegerField(default=0)),
                ("business_date", models.DateField()),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "نقد"), ("bank", "تحويل"), ("credit", "آجل")],
                        max_length=8,
                    ),
                ),
                ("amount_minor", models.BigIntegerField()),
                ("received_minor", models.BigIntegerField(blank=True, null=True)),
                ("change_minor", models.BigIntegerField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                ("unit_id", models.UUIDField()),
                ("unit_code", models.CharField(blank=True, default="", max_length=32)),
                ("factor_milli", models.BigIntegerField()),
                ("qty_milli", models.BigIntegerField()),
                ("unit_price_minor", models.BigIntegerField()),
                ("line_total_minor", models.BigIntegerField()),
                ("manual_price", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["tenant", "branch_id", "occurred_at"], name="sales_branch_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sales_sale_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"), name="sales_sale_invoice_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sales_payment_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sales_saleline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_sale"),
            rls.disable_sql("sales_sale"),
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_saleline"),
            rls.disable_sql("sales_saleline"),
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_payment"),
            rls.disable_sql("sales_payment"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "sales_saleline",
                "sales_saleline_sale_same_tenant",
                "tenant_id, sale_id",
                "sales_sale",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("sales_saleline", "sales_saleline_sale_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "sales_payment",
                "sales_payment_sale_same_tenant",
                "tenant_id, sale_id",
                "sales_sale",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("sales_payment", "sales_payment_sale_same_tenant"),
        ),
    ]
