# Generated by Django 5.2.17 on 2026-09-17 09:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("sales", "0002_sale_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sale_id", models.UUIDField()),
                ("party_id", models.UUIDField()),
                ("branch_id", models.UUIDField()),
                ("device_id", models.UUIDField()),
                ("requested_by_user_id", models.UUIDField()),
                ("requested_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("credit_limit_minor", models.BigIntegerField()),
                ("balance_after_minor", models.BigIntegerField()),
                ("reason", models.CharField(max_length=300)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="sales_creditoverride_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_creditoverride"),
            rls.disable_sql("sales_creditoverride"),
        ),
    ]
