# Generated by Django 5.2.17 on 2026-09-17 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("sales", "0003_credit_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_sale_id", models.UUIDField()),
                ("second_sale_id", models.UUIDField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("both_real", "الاثنان بيعان حقيقيان"),
                            ("reverse", "إلغاء المستند الثاني"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="sales_duplicatedecision_tenant_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DuplicateReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reported_by_user_id", models.UUIDField()),
                ("reported_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_reports",
                        to="sales.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="sales_duplicatereport_tenant_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("branch_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("duplicate", "تكرار تجاري"), ("correction", "تصحيح")],
                        default="duplicate",
                        max_length=16,
                    ),
                ),
                ("kept_sale_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.CharField(max_length=300)),
                ("decided_by_user_id", models.UUIDField()),
                ("decided_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="sales.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="sales_salereversal_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "sale"), name="sales_salereversal_once"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_duplicatedecision"),
            rls.disable_sql("sales_duplicatedecision"),
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_duplicatereport"),
            rls.disable_sql("sales_duplicatereport"),
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_salereversal"),
            rls.disable_sql("sales_salereversal"),
        ),
    ]
