# Generated by Django 5.2.17 on 2026-09-17 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("sales", "0004_duplicates_reversal"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("return_number", models.CharField(max_length=40)),
                ("branch_id", models.UUIDField()),
                ("device_id", models.UUIDField()),
                ("shift_id", models.UUIDField(blank=True, null=True)),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("party_id", models.UUIDField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "صالحة — تعود للمخزون"),
                            ("damaged", "تالفة — إلى الحجر أو الهالك"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[("cash", "نقداً من الصندوق"), ("credit", "خصماً من ذمة العميل")],
                        max_length=8,
                    ),
                ),
                ("total_minor", models.BigIntegerField()),
                ("cash_minor", models.BigIntegerField(default=0)),
                ("credit_minor", models.BigIntegerField(default=0)),
                ("exceeds_original", models.BooleanField(default=False)),
                ("business_date", models.DateField()),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.sale",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("factor_milli", models.BigIntegerField()),
                ("qty_milli", models.BigIntegerField()),
                ("unit_price_minor", models.BigIntegerField()),
                ("line_total_minor", models.BigIntegerField()),
                (
                    "sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.saleline",
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.salereturn",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sales_salereturn_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "return_number"), name="sales_salereturn_number_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sales_salereturnline_tenant_id"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_salereturn"),
            rls.disable_sql("sales_salereturn"),
        ),
        migrations.RunSQL(
            rls.enable_sql("sales_salereturnline"),
            rls.disable_sql("sales_salereturnline"),
        ),
    ]
