# Generated by Django 5.2.17 on 2026-09-15 20:50

import django.db.models.deletion
from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_rls_sessions_pin"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sync_state",
                        serialize=False,
                        to="core.tenant",
                    ),
                ),
                ("sync_epoch", models.CharField(max_length=64)),
                ("sync_counter", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_id", models.UUIDField()),
                ("kind", models.CharField(max_length=64)),
                ("op_version", models.PositiveSmallIntegerField()),
                ("device", models.UUIDField()),
                ("actor_user", models.UUIDField()),
                ("members_hash", models.CharField(max_length=64)),
                ("hash_version", models.PositiveSmallIntegerField()),
                ("sync_epoch", models.CharField(max_length=64)),
                ("server_seq", models.BigIntegerField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("entity", models.CharField(max_length=64)),
                ("entity_id", models.UUIDField()),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("server_seq", models.BigIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="sync.operation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuarantinedOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_id", models.UUIDField()),
                ("device", models.UUIDField()),
                (
                    "reason",
                    models.CharField(
                        choices=[("conflicted", "تعارض"), ("rejected", "مرفوضة")], max_length=12
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("detail", models.TextField(blank=True, default="")),
                ("original", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, default="", max_length=200)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["tenant", "server_seq"], name="sync_op_seq_idx"),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sync_operation_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "operation_id"), name="sync_operation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sync_member_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("tenant", "entity", "entity_id"), name="sync_member_entity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("tenant", "server_seq"), name="sync_member_seq_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="quarantinedoperation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sync_quarantine_tenant_id"
            ),
        ),
    ]
