# Generated by Django 5.2.17 on 2026-09-16 09:25

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_tenants_units_payment_creation"),
        ("sync", "0003_log_manifest_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BootstrapImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sync_epoch", models.CharField(max_length=64)),
                ("cutoff_server_seq", models.BigIntegerField()),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("scopes", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bootstrap_images",
                        to="core.device",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bootstrap_images",
                        to="sync.snapshot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BootstrapPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("group", models.CharField(max_length=20)),
                ("page_no", models.PositiveIntegerField()),
                ("entities", models.JSONField(default=list)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="sync.bootstrapimage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bootstrapimage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sync_bootstrapimage_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="bootstrappage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="sync_bootstrappage_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="bootstrappage",
            constraint=models.UniqueConstraint(
                fields=("image", "group", "page_no"), name="sync_bootstrappage_unique_page"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("sync_bootstrapimage"), rls.disable_sql("sync_bootstrapimage")
        ),
        migrations.RunSQL(
            rls.enable_sql("sync_bootstrappage"), rls.disable_sql("sync_bootstrappage")
        ),
    ]
