# Generated by Django 5.2.17 on 2026-09-18 11:01

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("sync", "0005_quarantine_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reference", models.CharField(max_length=32)),
                ("device", models.UUIDField()),
                ("user", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("app_version", models.CharField(blank=True, default="", max_length=40)),
                ("payload", models.JSONField()),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="sync_supportreport_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "reference"), name="sync_supportreport_reference"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("sync_supportreport"), rls.disable_sql("sync_supportreport")
        ),
    ]
