# Generated by Django 5.2.17 on 2026-09-18 11:45

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("sync", "0006_support_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupCopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device", models.UUIDField()),
                ("user", models.UUIDField()),
                ("file_name", models.CharField(max_length=200)),
                ("exported_at", models.DateTimeField()),
                ("size_bytes", models.BigIntegerField()),
                ("counts", models.JSONField(default=dict)),
                ("envelope", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="sync_backupcopy_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(rls.enable_sql("sync_backupcopy"), rls.disable_sql("sync_backupcopy")),
    ]
