# Generated by Django 5.2.17 on 2026-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0007_backup_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarantinedoperation",
            name="actor_user",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quarantinedoperation",
            name="reason",
            field=models.CharField(
                choices=[("conflicted", "تعارض"), ("rejected", "مرفوضة"), ("recovered", "مسترد")],
                max_length=12,
            ),
        ),
    ]
