# Generated by Django 5.2.17 on 2026-09-16 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0009_unit_decimal_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device_id", models.UUIDField()),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=200)),
                ("device_name", models.CharField(blank=True, default="", max_length=200)),
                ("opening_float_minor", models.BigIntegerField()),
                ("business_date", models.DateField()),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "مفتوحة"), ("closed", "مقفلة")],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("expected_cash_at_close_minor", models.BigIntegerField(blank=True, null=True)),
                ("counted_cash_minor", models.BigIntegerField(blank=True, null=True)),
                ("server_seq", models.BigIntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftCashMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("signed_amount_minor", models.BigIntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("actor_user_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="shifts.shift",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["tenant", "branch", "state"], name="shifts_branch_state"),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="shifts_shift_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftcashmovement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="shifts_cashmovement_tenant_id"
            ),
        ),
        migrations.RunSQL(rls.enable_sql("shifts_shift"), rls.disable_sql("shifts_shift")),
        migrations.RunSQL(
            rls.enable_sql("shifts_shiftcashmovement"),
            rls.disable_sql("shifts_shiftcashmovement"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "shifts_shift",
                "shifts_shift_branch_same_tenant",
                "tenant_id, branch_id",
                "core_branch",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("shifts_shift", "shifts_shift_branch_same_tenant"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "shifts_shiftcashmovement",
                "shifts_cashmovement_shift_same_tenant",
                "tenant_id, shift_id",
                "shifts_shift",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql(
                "shifts_shiftcashmovement", "shifts_cashmovement_shift_same_tenant"
            ),
        ),
    ]
