# Generated by Django 5.2.17 on 2026-09-16 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("shifts", "0001_shifts"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="count_status",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="shift",
            name="counted_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="shift",
            name="counted_by_user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="denominations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="shift",
            name="expected_source",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="shift",
            name="witness_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="shift",
            name="witness_user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shiftcashmovement",
            name="actor_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="shiftcashmovement",
            name="authorized_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="shiftcashmovement",
            name="authorized_by_user_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shiftcashmovement",
            name="number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="shiftcashmovement",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="shifts.shiftcashmovement",
            ),
        ),
        migrations.CreateModel(
            name="CashMovementRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("amount_minor", models.BigIntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("requested_by_user_id", models.UUIDField()),
                ("requested_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=16)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="shifts.shift",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="shifts_cashmovementrequest_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("shifts_cashmovementrequest"),
            rls.disable_sql("shifts_cashmovementrequest"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "shifts_cashmovementrequest",
                "shifts_cashmovementrequest_shift_same_tenant",
                "tenant_id, shift_id",
                "shifts_shift",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql(
                "shifts_cashmovementrequest", "shifts_cashmovementrequest_shift_same_tenant"
            ),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "shifts_shiftcashmovement",
                "shifts_cashmovement_reverses_same_tenant",
                "tenant_id, reverses_id",
                "shifts_shiftcashmovement",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql(
                "shifts_shiftcashmovement", "shifts_cashmovement_reverses_same_tenant"
            ),
        ),
    ]
