# Generated by Django 5.2.17 on 2026-09-16 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
        ("shifts", "0002_cash_movements_close"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftcashmovement",
            name="received_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="CashAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("signed_amount_minor", models.BigIntegerField()),
                ("approved_by_user_id", models.UUIDField()),
                ("approved_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("late_item_ids", models.JSONField(default=list)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="shifts.shift",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="shifts_cashadjustment_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("shifts_cashadjustment"),
            rls.disable_sql("shifts_cashadjustment"),
        ),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "shifts_cashadjustment",
                "shifts_cashadjustment_shift_same_tenant",
                "tenant_id, shift_id",
                "shifts_shift",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql(
                "shifts_cashadjustment", "shifts_cashadjustment_shift_same_tenant"
            ),
        ),
    ]
