# Generated by Django 5.2.17 on 2026-09-15 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("display_name", models.CharField(max_length=200)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_platform_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=6)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("base_currency", models.CharField(max_length=3)),
                ("base_currency_exponent", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserBranchAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("prefix", models.CharField(max_length=4)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "فعّال"), ("revoked", "ملغى")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="core.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="core.tenant",
                    ),
                ),
                ("locale", models.JSONField(blank=True, default=dict)),
                ("sales", models.JSONField(blank=True, default=dict)),
                ("inventory", models.JSONField(blank=True, default=dict)),
                ("pos", models.JSONField(blank=True, default=dict)),
                ("branding", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_currency__regex", "^[A-Z]{3}$")),
                name="core_tenant_currency_iso4217",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_currency_exponent__gte", 0), ("base_currency_exponent__lte", 4)
                ),
                name="core_tenant_exponent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                fields=("id", "base_currency", "base_currency_exponent"),
                name="core_tenant_currency_target",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="userbranchaccess",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_access",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="userbranchaccess",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.role"
            ),
        ),
        migrations.AddField(
            model_name="userbranchaccess",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="userbranchaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branch_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="core_role_tenant_id"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="core_role_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="core_device_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("tenant", "prefix"), name="core_device_prefix_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.CheckConstraint(
                condition=models.Q(("prefix__regex", "^[A-Z0-9]{1,4}$")),
                name="core_device_prefix_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="core_branch_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="core_branch_code_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", "^[A-Z0-9]{2,6}$")),
                name="core_branch_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="core_user_tenant_id"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("tenant", "username"), name="core_user_username_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tenant__isnull", True), ("is_platform_staff", True)),
                    models.Q(("tenant__isnull", False), ("is_platform_staff", False)),
                    _connector="OR",
                ),
                name="core_user_platform_xor_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="userbranchaccess",
            constraint=models.UniqueConstraint(fields=("tenant", "id"), name="core_uba_tenant_id"),
        ),
        migrations.AddConstraint(
            model_name="userbranchaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "branch"), name="core_uba_user_branch"
            ),
        ),
    ]
