# Generated by Django 5.2.17 on 2026-09-16 08:49

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import core.ids
from core.db import rls

"""وحدات وطرق دفع (بمستأجر: RLS ومفاتيح مركبة) وسجل إنشاء المنشأة (منصة فقط) — T1.2."""

PLATFORM_ONLY = """
ALTER TABLE {t} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {t} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS {t}_platform_only ON {t};
CREATE POLICY {t}_platform_only ON {t}
  USING (sting_is_platform()) WITH CHECK (sting_is_platform());
"""
DROP_POLICY = """
DROP POLICY IF EXISTS {t}_platform_only ON {t};
ALTER TABLE {t} NO FORCE ROW LEVEL SECURITY;
ALTER TABLE {t} DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_accounts_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=60)),
                ("is_cash", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_paymentmethod_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "code"), name="core_paymentmethod_code_per_tenant"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantCreation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_request_id", models.UUIDField()),
                ("sector", models.CharField(max_length=40)),
                ("created_counts", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creations",
                        to="core.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "client_request_id"), name="core_tenantcreation_request"
                    )
                ],
            },
            managers=[
                ("unscoped", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=60)),
                ("is_base", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "id"), name="core_unit_tenant_id"),
                    models.UniqueConstraint(
                        fields=("tenant", "code"), name="core_unit_code_per_tenant"
                    ),
                ],
            },
        ),
        migrations.RunSQL(rls.enable_sql("core_unit"), rls.disable_sql("core_unit")),
        migrations.RunSQL(
            rls.enable_sql("core_paymentmethod"), rls.disable_sql("core_paymentmethod")
        ),
        migrations.RunSQL(
            PLATFORM_ONLY.format(t="core_tenantcreation"),
            DROP_POLICY.format(t="core_tenantcreation"),
        ),
    ]
