# Generated by Django 5.2.17 on 2026-09-16 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_tenants_units_payment_creation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invitee_identifier", models.CharField(max_length=254)),
                ("token_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_invitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitations",
                        to="core.branch",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_invitation_tenant_id"
                    ),
                    models.UniqueConstraint(fields=("token_hash",), name="core_invitation_token"),
                ],
            },
        ),
        migrations.RunSQL(rls.enable_sql("core_invitation"), rls.disable_sql("core_invitation")),
        migrations.RunSQL(
            rls.composite_fk_sql(
                "core_invitation",
                "core_invitation_branch_same_tenant",
                "tenant_id, branch_id",
                "core_branch",
                "tenant_id, id",
            ),
            rls.drop_constraint_sql("core_invitation", "core_invitation_branch_same_tenant"),
        ),
    ]
