# Generated by Django 5.2.17 on 2026-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_invitations"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="reported_pending",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="reported_pending_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="revoke_after_upload",
            field=models.BooleanField(default=False),
        ),
    ]
