# Generated by Django 5.2.17 on 2026-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_session_pending_revoke"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="decimal_places",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(("decimal_places__lte", 3)), name="core_unit_decimal_places_max3"
            ),
        ),
    ]
