# Generated by Django 5.2.17 on 2026-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_unit_decimal_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="wipe_acknowledgement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="device",
            name="wiped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="wiped_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "فعّال"),
                    ("revoked", "ملغى"),
                    ("frozen", "مجمَّد"),
                    ("wiped", "ممحو"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
