# Generated by Django 5.2.17 on 2026-09-18 18:31

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_device_freeze_wipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user", models.UUIDField()),
                ("endpoint", models.TextField()),
                ("endpoint_sha256", models.CharField(max_length=64)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=100)),
                ("user_agent", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=120)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_endpoints",
                        to="core.device",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_deviceendpoint_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "endpoint_sha256"), name="core_deviceendpoint_unique"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_deviceendpoint"), rls.disable_sql("core_deviceendpoint")
        ),
    ]
