# Generated by Django 5.2.17 on 2026-09-19 06:36

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_device_endpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("value", models.CharField(max_length=20)),
                ("limit_minor", models.BigIntegerField(blank=True, null=True)),
                ("period", models.CharField(blank=True, default="", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_rolepermission_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "role", "key"), name="core_rolepermission_role_key"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_rolepermission"), rls.disable_sql("core_rolepermission")
        ),
    ]
