# Generated by Django 5.2.17 on 2026-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_role_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deactivated_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
