# Generated by Django 5.2.17 on 2026-09-19 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_user_deactivation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("plan_code", models.CharField(max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[("trial", "تجريبية"), ("active", "سارية"), ("expired", "منتهية")],
                        default="trial",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("extra_features", models.JSONField(blank=True, default=list)),
                ("renewal_amount_minor", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_tenantsubscription_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant",), name="core_tenantsubscription_one_per_tenant"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_tenantsubscription"), rls.disable_sql("core_tenantsubscription")
        ),
    ]
