# Generated by Django 5.2.17 on 2026-09-19 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_tenant_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionProof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reference", models.CharField(max_length=64)),
                ("plan_code", models.CharField(max_length=20)),
                ("amount_minor", models.BigIntegerField()),
                ("period_label", models.CharField(blank=True, default="", max_length=40)),
                ("image_name", models.CharField(blank=True, default="", max_length=200)),
                ("image_size", models.BigIntegerField(default=0)),
                ("image_data", models.TextField(blank=True, default="")),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "معلّق للمراجعة"),
                            ("approved", "معتمد"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("rejection_reason", models.CharField(blank=True, default="", max_length=300)),
                ("extension_days", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_subscriptionproof_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "reference"), name="core_subscriptionproof_reference"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_subscriptionproof"), rls.disable_sql("core_subscriptionproof")
        ),
    ]
