# Generated by Django 5.2.17 on 2026-09-19 08:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_subscription_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="updated_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor_user_id", models.UUIDField(blank=True, null=True)),
                ("actor_name", models.CharField(blank=True, default="", max_length=200)),
                ("actor_role", models.CharField(blank=True, default="", max_length=60)),
                ("kind", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.CharField(blank=True, default="", max_length=400)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("sensitive", models.BooleanField(default=False)),
                ("ref_entity", models.CharField(blank=True, default="", max_length=64)),
                ("ref_id", models.UUIDField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.branch",
                    ),
                ),
                (
                    "refers_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.auditevent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["tenant", "at"], name="core_audit_tenant_at")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_auditevent_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(rls.enable_sql("core_auditevent"), rls.disable_sql("core_auditevent")),
    ]
