# Generated by Django 5.2.17 on 2026-09-19 08:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_audit_and_settings_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="former_owner_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OwnershipTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("from_user_id", models.UUIDField()),
                ("from_user_name", models.CharField(max_length=200)),
                ("to_user_id", models.UUIDField()),
                ("to_user_name", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار تأكيد المالك الجديد"),
                            ("confirmed", "نُفّذ"),
                            ("cancelled", "أُلغي"),
                            ("expired", "انقضى"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_ownershiptransfer_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_ownershiptransfer"), rls.disable_sql("core_ownershiptransfer")
        ),
    ]
