# Generated by Django 5.2.17 on 2026-09-19 12:05

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_ownership_transfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "report",
                    models.CharField(
                        choices=[
                            ("sales", "تقرير المبيعات"),
                            ("receivables", "تقرير الذمم"),
                            ("stock", "تقرير المخزون"),
                            ("cash", "تقرير الصندوق"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "fmt",
                    models.CharField(
                        choices=[("html", "HTML"), ("csv", "CSV")], default="html", max_length=4
                    ),
                ),
                ("range_start", models.DateField()),
                ("range_end", models.DateField()),
                ("branch_id", models.UUIDField(blank=True, null=True)),
                ("file_name", models.CharField(max_length=240)),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(default=1)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("body", models.TextField()),
                ("generated_by_user_id", models.UUIDField()),
                ("generated_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("open_count", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_reportexport_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_reportexport"), rls.disable_sql("core_reportexport")
        ),
    ]
