# Generated by Django 5.2.17 on 2026-09-19 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_report_export"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("operational", "تشغيلي"),
                            ("account", "حسابي"),
                            ("marketing", "تسويقي"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, default="", max_length=500)),
                ("href", models.CharField(blank=True, default="", max_length=200)),
                ("screen", models.CharField(blank=True, default="", max_length=16)),
                ("needs_action", models.BooleanField(default=False)),
                ("owner_only", models.BooleanField(default=False)),
                ("branch_id", models.UUIDField(blank=True, null=True)),
                ("dedupe_key", models.CharField(max_length=120)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("read_user_ids", models.JSONField(default=list)),
                ("link_token", models.CharField(max_length=64)),
                ("link_expires_at", models.DateTimeField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "occurred_at"], name="core_notif_tenant_at")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_notification_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "dedupe_key"), name="core_notification_dedupe_once"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("prefs", models.JSONField(default=dict)),
                ("destination_email", models.EmailField(blank=True, default="", max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_notificationpreference_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "user"), name="core_notificationpreference_once_per_user"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_notification"), rls.disable_sql("core_notification")
        ),
        migrations.RunSQL(
            rls.enable_sql("core_notificationpreference"),
            rls.disable_sql("core_notificationpreference"),
        ),
    ]
