# Generated by Django 5.2.17 on 2026-09-19 12:52

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("message", models.TextField(blank=True, default="")),
                ("channel", models.CharField(default="sms", max_length=8)),
                ("audience_rules", models.JSONField(default=dict)),
                ("audience_count", models.PositiveIntegerField(default=0)),
                ("excluded_count", models.PositiveIntegerField(default=0)),
                ("parts", models.PositiveIntegerField(default=1)),
                ("cost_messages", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("pending_approval", "بانتظار الاعتماد"),
                            ("scheduled", "مجدولة"),
                            ("sending", "جارية"),
                            ("done", "اكتملت"),
                            ("cancelled", "أُلغيت"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("night_confirmed", models.BooleanField(default=False)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("created_by_user_id", models.UUIDField()),
                ("created_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "id"), name="core_campaign_tenant_id")
                ],
            },
        ),
        migrations.RunSQL(rls.enable_sql("core_campaign"), rls.disable_sql("core_campaign")),
    ]
