# Generated by Django 5.2.17 on 2026-09-19 13:11

import django.db.models.deletion
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_campaigns"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="approved_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="campaign",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="cancelled_by_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.CreateModel(
            name="CampaignMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("party_id", models.UUIDField()),
                ("phone", models.CharField(max_length=32)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "في الطابور"),
                            ("sent", "أُرسلت للمزوّد"),
                            ("accepted", "قبِلها المزوّد"),
                            ("delivered", "أكّد المزوّد تسليمها"),
                            ("unconfirmed", "غير محسومة"),
                            ("failed_permanent", "فشلت نهائياً"),
                            ("failed_temporary", "رفض المزوّد مؤقتاً"),
                            ("opted_out", "أوقف التسويق أثناء الحملة"),
                            ("cancelled", "أُلغيت قبل الإرسال"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=120)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("provider_ref", models.CharField(blank=True, default="", max_length=64)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.campaign",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_campaignmessage_tenant_id"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "campaign", "party_id"),
                        name="core_campaignmessage_once_per_party",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_campaignmessage"), rls.disable_sql("core_campaignmessage")
        ),
    ]
