# Generated by Django 5.2.17 on 2026-09-19 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_campaign_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.CharField(max_length=24, unique=True)),
                ("address", models.CharField(blank=True, default="", max_length=300)),
                ("hours", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PortalSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("phone", models.CharField(max_length=32)),
                ("phone_normalized", models.CharField(db_index=True, max_length=32)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("consent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("opt_out_at", models.DateTimeField(blank=True, null=True)),
                ("push_permission", models.CharField(blank=True, default="", max_length=12)),
                ("push_endpoint", models.TextField(blank=True, default="")),
                ("push_p256dh", models.CharField(blank=True, default="", max_length=200)),
                ("push_auth", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="campaignmessage",
            name="core_campaignmessage_once_per_party",
        ),
        migrations.AddField(
            model_name="campaign",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignmessage",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignmessage",
            name="subscriber_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaignmessage",
            name="party_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="campaignmessage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "campaign", "phone"), name="core_campaignmessage_once_per_phone"
            ),
        ),
        migrations.AddField(
            model_name="portalchannel",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="portalsubscriber",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalchannel",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="core_portalchannel_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsubscriber",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="core_portalsubscriber_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsubscriber",
            constraint=models.UniqueConstraint(
                fields=("tenant", "phone_normalized"), name="core_portalsubscriber_once_per_phone"
            ),
        ),
        migrations.RunSQL(
            rls.enable_sql("core_portalchannel"), rls.disable_sql("core_portalchannel")
        ),
        migrations.RunSQL(
            rls.enable_sql("core_portalsubscriber"), rls.disable_sql("core_portalsubscriber")
        ),
    ]
