# Generated by Django 5.2.17 on 2026-09-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_portal"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalsubscriber",
            name="channel_inbox",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portalsubscriber",
            name="channel_push",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="portalsubscriber",
            name="channel_sms",
            field=models.BooleanField(default=False),
        ),
    ]
