# Generated by Django 5.2.17 on 2026-09-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_portal_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsubscription",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="suspended_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
