# Generated by Django 5.2.17 on 2026-09-22 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_subscription_ops"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanCatalog",
            fields=[
                ("code", models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("blurb", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("trial", models.BooleanField(default=False)),
                ("trial_days", models.PositiveIntegerField(default=30)),
                ("max_branches", models.PositiveIntegerField(default=1)),
                ("max_devices", models.PositiveIntegerField(default=3)),
                ("max_users", models.PositiveIntegerField(blank=True, null=True)),
                ("campaign_quota", models.PositiveIntegerField(default=0)),
                ("features", models.JSONField(blank=True, default=list)),
                ("price_monthly_minor", models.BigIntegerField(default=0)),
                ("price_quarterly_minor", models.BigIntegerField(default=0)),
                ("price_yearly_minor", models.BigIntegerField(default=0)),
                ("next_price_monthly_minor", models.BigIntegerField(blank=True, null=True)),
                ("next_price_quarterly_minor", models.BigIntegerField(blank=True, null=True)),
                ("next_price_yearly_minor", models.BigIntegerField(blank=True, null=True)),
                ("next_price_effective_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.AddField(
            model_name="subscriptionproof",
            name="cycle",
            field=models.CharField(default="monthly", max_length=10),
        ),
        migrations.CreateModel(
            name="PlanChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("by_name", models.CharField(blank=True, default="", max_length=200)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="core.plancatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
    ]
