# Generated by Django 5.2.17 on 2026-09-22 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.ids
from core.db import rls


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_plan_cycle_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptCounter",
            fields=[
                ("year", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("last", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("tenant_name", models.CharField(max_length=200)),
                ("plan_code", models.CharField(max_length=20)),
                ("plan_name", models.CharField(max_length=60)),
                ("cycle", models.CharField(default="monthly", max_length=10)),
                ("cycle_label", models.CharField(default="شهري", max_length=20)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="SDG", max_length=3)),
                ("reference", models.CharField(max_length=64)),
                ("period_from", models.DateTimeField()),
                ("period_to", models.DateTimeField()),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("issued_by_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "proof",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="core.subscriptionproof",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "issued_at"], name="core_subreceipt_issued")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="core_subreceipt_tenant_id"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            rls.enable_sql("core_subscriptionreceipt"), rls.disable_sql("core_subscriptionreceipt")
        ),
    ]
