# Generated by Django 5.2.17 on 2026-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_subscription_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionproof",
            name="kind",
            field=models.CharField(default="renewal", max_length=10),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="next_plan_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
