# Generated by Django 5.2.17 on 2026-09-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_plan_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsubscription",
            name="extra_branches",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="extra_devices",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="extra_users",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
