# Generated by Django 5.2.17 on 2026-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_plan_user_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="plancatalog",
            name="addon_branch_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plancatalog",
            name="addon_device_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plancatalog",
            name="addon_user_minor",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionproof",
            name="addon_kind",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="subscriptionproof",
            name="addon_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="addon_branches",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="addon_devices",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="addon_users",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
