# Generated by Django 5.2.17 on 2026-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_addon_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsubscription",
            name="cycle",
            field=models.CharField(default="monthly", max_length=10),
        ),
    ]
