# Generated by Django 5.2.17 on 2026-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_pricing_decisions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualverificationrequest",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "تسجيل"),
                    ("recover", "استعادة"),
                    ("demo", "طلب جولة"),
                    ("track", "متابعة طلب"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "تسجيل"),
                    ("recover", "استعادة"),
                    ("demo", "طلب جولة"),
                    ("track", "متابعة طلب"),
                ],
                max_length=10,
            ),
        ),
    ]
