# Generated by Django 5.2.17 on 2026-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_demo_request_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
